version: '3.9'
services:
  nodeserver:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - 80:3000
    networks:
      - frontend
      - backend
    depends_on:
      mymongodb:
        condition: service_healthy

  mymongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    hostname: mongodbhost
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: products
    volumes:
      - mongo-data:/data/db
    networks:
      - backend
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  mongo-data: 
  
networks:
  frontend:
    name: frontend
  backend:
    name: backend
    
